<?php
/**
 * Title: Gutenberg Changelog
 * Slug: gt-2025/gutenberg-changelog
 * Categories: 
 */
?>
<!-- wp:media-text {"mediaId":11624,"mediaType":"image","mediaWidth":21,"imageFill":false} -->
<div class="wp-block-media-text alignwide is-stacked-on-mobile" style="grid-template-columns:21% auto"><figure class="wp-block-media-text__media"><img src="https://i0.wp.com/gutenbergtimes.com/wp-content/uploads/2019/07/Gutenberg-Changelog-Logo-by-Mark-Uraine.png?fit=640%2C640&amp;ssl=1" alt="<?php esc_attr_e('Gutenberg Changelog logo by Mark Uraine ', 'gt-2025');?>" class="wp-image-11624 size-full"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…"} -->
<p><?php /* Translators: 1. is the start of a 'strong' HTML element, 2. is the end of a 'strong' HTML element, 3. is a 'br' HTML element, 4. is the start of a 'a' HTML element, 5. is the end of a 'a' HTML element, 6. is a 'br' HTML element, 7. is the start of a 'a' HTML element, 8. is the end of a 'a' HTML element, 9. is the start of a 'a' HTML element, 10. is the end of a 'a' HTML element, 11. is the start of a 'a' HTML element, 12. is the end of a 'a' HTML element, 13. is the start of a 'a' HTML element, 14. is the end of a 'a' HTML element, 15. is the start of a 'a' HTML element, 16. is the end of a 'a' HTML element, 17. is the start of a 'a' HTML element, 18. is the end of a 'a' HTML element */ 
echo sprintf( esc_html__( '%1$sSubscribe to our podcast: %2$s%3$s%4$sGutenberg Changelog%5$s, hosted by Mary Job and Birgit Pauli-Haack%6$s%7$sSpotify%8$s | %9$sGoogle%10$s | %11$siTunes%12$s | %13$sStitcher%14$s | %15$sOvercast%16$s%17$s%18$s', 'gt-2025' ), '<strong>', '</strong>', '<br>', '<a href="' . esc_url( 'https://gutenbergtimes.com/podcast' ) . '">', '</a>', '<br>', '<a href="' . esc_url( 'https://open.spotify.com/show/620NwVKQJGdTupy36zYxvg' ) . '">', '</a>', '<a href="' . esc_url( 'https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Itjbhizpz37fthuhvnu5sfeooqy?t%3DGutenberg_Changelog%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16' ) . '">', '</a>', '<a href="' . esc_url( 'https://podcasts.apple.com/us/podcast/gutenberg-changelog/id1469294475' ) . '">', '</a>', '<a href="' . esc_url( 'https://www.stitcher.com/podcast/gutenberg-times/gutenberg-changelog' ) . '">', '</a>', '<a href="' . esc_url( 'https://overcast.fm/itunes1469294475/gutenberg-changelog' ) . '">', '</a>', '<a href="' . esc_url( 'https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Itjbhizpz37fthuhvnu5sfeooqy?t%3DGutenberg_Changelog%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16' ) . '">', '</a>' ); ?></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->