<?php
/**
 * Title: Podcast Logos
 * Slug: gt-2025/podcast-logos
 * Categories: 
 */
?>
<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size"><?php /* Translators: 1. is the start of a 'strong' HTML element, 2. is the start of a 'a' HTML element, 3. is the end of a 'a' HTML element, 4. is the end of a 'strong' HTML element, 5. is a 'br' HTML element, 6. is the start of a 'a' HTML element, 7. is the end of a 'a' HTML element, 8. is the start of a 'a' HTML element, 9. is the end of a 'a' HTML element, 10. is the start of a 'a' HTML element, 11. is the end of a 'a' HTML element, 12. is the start of a 'a' HTML element, 13. is the end of a 'a' HTML element, 14. is the start of a 'a' HTML element, 15. is the end of a 'a' HTML element, 16. is a 'br' HTML element, 17. is the start of a 'a' HTML element, 18. is the end of a 'a' HTML element, 19. is the start of a 'a' HTML element, 20. is the end of a 'a' HTML element, 21. is the start of a 'a' HTML element, 22. is the end of a 'a' HTML element, 23. is the start of a 'a' HTML element, 24. is the end of a 'a' HTML element */ 
echo sprintf( esc_html__( '%1$sSubscribe to the %2$sGutenberg Changelog%3$s podcast via your favorite podcast apps!%4$s%5$s🎙️ %6$sSpotify%7$s | %8$sGoogle%9$s | %10$siTunes%11$s | %12$sPocketCasts%13$s | %14$sStitcher%15$s |%16$s🎙️ %17$sPod Bean%18$s | %19$sCastBox%20$s | %21$sPodchaser%22$s | %23$sRSS Feed%24$s ', 'gt-2025' ), '<strong>', '<a href="' . esc_url( 'https://gutenbergtimes.com/podcast/' ) . '">', '</a>', '</strong>', '<br>', '<a href="' . esc_url( 'https://open.spotify.com/show/620NwVKQJGdTupy36zYxvg?mc_cid=4b6c9f88fe' ) . '">', '</a>', '<a href="' . esc_url( 'https://podcasts.google.com/feed/aHR0cHM6Ly9ndXRlbmJlcmd0aW1lcy5jb20vZmVlZC9wb2RjYXN0' ) . '">', '</a>', '<a href="' . esc_url( 'https://podcasts.apple.com/us/podcast/gutenberg-changelog/id1469294475' ) . '">', '</a>', '<a href="' . esc_url( 'https://pca.st/podcast/f8445ec0-7508-0137-f267-1d245fc5f9cf' ) . '">', '</a>', '<a href="' . esc_url( 'https://www.stitcher.com/show/gutenberg-changelog' ) . '">', '</a>', '<br>', '<a href="' . esc_url( 'https://www.podbean.com/podcast-detail/chi7j-9904a/Gutenberg-Changelog-Podcast' ) . '">', '</a>', '<a href="' . esc_url( 'https://castbox.fm/channel/Gutenberg-Changelog-id2173375' ) . '">', '</a>', '<a href="' . esc_url( 'https://www.podchaser.com/podcasts/gutenberg-changelog-878239/' ) . '">', '</a>', '<a href="' . esc_url( 'https://gutenbergtimes.com/feed/podcast' ) . '">', '</a>' ); ?></p>
<!-- /wp:paragraph -->